### ISSUE TITLE
Exact route / ver3

### ISSUE THREAD

**Issue by JacoboAlonso** [scssyworks/silkrouter#92]
Hi @scssyworks 

 I'm using the jquery version of silkrouter 3.5.9 and i have a problem with the find and return the exact route. ejm:

if i have in my definition one route "father" /names and others "sub"routes ejem: /names/jhonDoe |  /names/Peter  and try to goTo the sub route "/names/Peter" the router find me 2 coincidance the subroute and the route father,

I have any solution for this case and return only the exact route in this case only the subroute /names/Peter? 

Regards

**Comment by scssyworks** [comment]
Hi @JacoboAlonso 

Can you share me a gist of your code and exact problem you are facing? So far what I have understood is you have attached two listeners like so:

```js
router('/names', () => {});
router('/names/Peter', () => {});
```

Are you getting both these listeners invoked when path `/names/Peter` is set?

**Comment by JacoboAlonso** [comment]
Hi @scssyworks 

Thanks for answer me.

That is exactly what is happening now return two linsterners and that the expected behavior would be that if it matches "/names/Peter" it should not add to /names"

I don't know if the library support any parameter when if i had a match return only the first coincidance

Regards

**Comment by scssyworks** [comment]
Hi @JacoboAlonso,

I have published a version 3.6.0. Please install using following command:

```sh
npm install silkrouter@legacy
```

However, **I have not made any specific code changes** and in my testing I am not able to replicate the same issue. Screenshots are attached below for your reference:

<img width="477" alt="Screen Shot 2021-11-10 at 9 10 55 PM" src="https://user-images.githubusercontent.com/30828693/141148760-8ff747f0-ca56-4dbe-8f5b-8e62d9aa53d2.png">
<img width="441" alt="Screen Shot 2021-11-10 at 9 32 01 PM" src="https://user-images.githubusercontent.com/30828693/141148770-317d16d5-a468-4264-92df-674a6787db45.png">
<img width="440" alt="Screen Shot 2021-11-10 at 9 32 11 PM" src="https://user-images.githubusercontent.com/30828693/141148779-9f5913d2-3322-4ccd-ba7e-5b53f727a540.png">

You can see that when ``/names/Peter`` route is set then message "Peter" is printed. When only ``/names`` route is set then "All names" message is printed. Same if the case when page is refreshed.

You can checkout the DEMO project here: https://github.com/scssyworks/jqueryrouter-example

**It would really help if you can share your code with me so that I can help you better.**

I will keeping this ticket open for next 7 days. Also consider upgrading to version 4 (the latest version) which is far more customizable and easy to implement.

**Comment by JacoboAlonso** [comment]
Hi @scssyworks 

I have tried to reproduce your demo and indeed in your demo it returns a match, reviewing your demo and my explanation I apologize that I think I could not reproduce the problem exactly

- The first thinks is im used the lib in .js by way cdn https://cdn.jsdelivr.net/npm/silkrouter@3.6.0 but the cdn only exist the 5.39 but with this version my problem persist

- the definition the my routes is 
![image](https://user-images.githubusercontent.com/93601560/141282654-20758045-a00e-48db-8452-531804d9d96a.png)

![image](https://user-images.githubusercontent.com/93601560/141282942-d2f37011-ffc2-4ef3-b74d-7f3f6a717057.png)

- when invoke the route example, "/names/peter/lastname" when peter is a dinamic name by params the router match 2 the first match "/names/:callName/lastname" and "/names/:callName", i think the problem is when in the route used a dinamy params

![image](https://user-images.githubusercontent.com/93601560/141284815-2dd61659-0216-4ad0-bb28-107be8a21593.png)

if your need more information write me

Thank a lot for the help

**Comment by scssyworks** [comment]
@JacoboAlonso can you try using a non-cdn version? Meanwhile I will try to figure out the issue with cdn version.
